config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # ゲストログイン
  devise_scope :user do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    get "/" => "homes#top"
    resources :tags, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      # ユーザーの投稿一覧
      member do
        get :posts
      end
    end

    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end


  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"

    resources :users, only: [:show, :edit, :update, :destroy] do
      get "/unsubscribe" => "users#unsubscribe"
      # ブックマークした投稿一覧表示
      member do
        get :bookmarks
      end
    end

    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      # 下書き一覧
      collection do
        get "draft_index"
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :name, presence: true, length: { maximum: 10 }
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!


  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      @tags = Tag.all
      render "index"
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
    else
      render "edit"
    end
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_error.html.erb
<div class="row">
  <div class="col-md-8 offset-2">
  <% if obj.errors.any? %>
  <%= obj.errors.count %>件のエラーが発生しました
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  </div>
</div>

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto pt-5">
      <h3><span class="admin-title">タグ編集</span></h3>
    </div>
  </div>
</div>

<div class="container py-5">
   <%= render "error", obj: @tag %>
   <div class="row">
    <div class="col-md-6 mx-auto py-5">
      <%= form_with model: @tag, url: admin_tag_path, method: :patch do |f| %>
        <div class="form-group d-flex justify-content-around">
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true %>
          <%= f.submit '更新する', class: 'btn btn-outline-success btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto pt-5">
      <h3><span class="admin-title">タグ一覧/追加</span></h3>
    </div>
  </div>
</div>

<div class="container">
  <%= render "error", obj: @tag %>
  <div class="row pt-5">
    <div class="col-md-8 mx-auto text-right">
      <%= form_with model: @tag, url: admin_tags_path do |f| %>
        <div class="form-group d-flex justify-content-center">
          <%= f.label :name %>：
          <%= f.text_field :name, autofocus: true %>
          <%= f.submit '追加する', class: 'btn btn-outline-success btn-sm ml-2' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row py-5">
    <div class="col-md-6 offset-3 text-center">
      <table class="table">
        <thead>
          <tr>
            <th>タグ名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
            <tr>
              <td><%= tag.name %></td>
              <td><%= link_to "編集する", edit_admin_tag_path(tag.id), class: 'btn btn-outline-info btn-sm' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>