config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # ゲストログイン
  devise_scope :user do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    get "/" => "homes#top"
    resources :tags, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      # ユーザーの投稿一覧
      member do
        get :posts
      end
    end

    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end


  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"

    resources :users, only: [:show, :edit, :update, :destroy] do
      get "/unsubscribe" => "users#unsubscribe"
      # ブックマークした投稿一覧表示
      member do
        get :bookmarks
      end
    end

    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      # 下書き一覧
      collection do
        get "draft_index"
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_one_attached :post_image

  geocoded_by :address
  after_validation :geocode

  scope :latest, -> { order(created_at: :desc) }
  scope :draft, -> { where(is_draft: true) }
  scope :release, -> { where(is_draft: false) }


  with_options presence: true, on: :publicize do
    validates :title
    validates :body
    validates :airport
  end

  validates :title, length: { maximum: 20 }, on: :publicize
  validates :body, length: { maximum: 80 }, on: :publicize


  def get_post_image
    unless post_image.attached?
      file_path = Rails.root.join("app/javascript/images/no_post_image.png")
      post_image.attach(io: File.open(file_path), filename: "no_post_image.png", content_type: "image/png")
    end
    post_image
  end

  # ブックマークがあるか
  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.where(is_draft: false).order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @comments = @post.post_comments.order(created_at: :desc).page(params[:page]).per(5)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 offset-2 pt-5">
      <h3><span class="admin-title">みんなの投稿一覧</span></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mx-auto pt-5">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>ユーザー</th>
              <th>タイトル</th>
              <th>投稿日時</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
            <tr>
              <td><%= post.user.name %></td>
              <td><%= post.title %></td>
              <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
              <td><%= link_to '詳細へ', admin_post_path(post), class: 'btn btn-sm btn-outline-info' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mx-auto pt-5 d-flex justify-content-center">
      <p><%= paginate @posts %></p>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container my-5 py-5">
  <!--投稿詳細-->
  <%= render "/public/posts/post-detail", post: @post %>

  <div class="row offset-md-1 my-2">
    <h5 class="comment-title ml-1"><i class="far fa-comments"></i> コメント</h5>
  </div>
  <!--コメントエリア-->
  <div class="row">
    <div class="comment-area col-md-5 offset-md-1">
      <% unless @post.post_comments.present? %>
        <p class="text-muted">まだコメントがありません。</p>
      <% end %>

      <% @comments.each do |post_comment| %>
        <%= image_tag post_comment.user.get_profile_image(30,30), class: 'rounded-circle border' %>
        <%= link_to post_comment.user.name, admin_user_path(post_comment.user), class: 'text-dark' %>
        <span>  : <%= post_comment.comment %></span>
        <small class="text-muted"><p class="d-flex justify-content-end pr-5">
          <%= post_comment.created_at.strftime('%Y/%m/%d') %>
          <%= link_to admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, class: 'text-dark border-bottom text-muted', data: {confirm: "このコメントを削除しますか？"} do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </p></small>
      <% end %>

      <div class="row">
        <div class="col-md-6 mx-auto pt-2 d-flex justify-content-center">
          <p><%= paginate @comments %></p>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="not-signin d-flex">
          <%= link_to '※この投稿を削除する（管理者）※', admin_post_path(@post), method: :delete, class: 'text-danger h5', data: {confirm: "本当に削除しますか？"}  %>
      </div>
    </div>
  </div>
</div>