config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # ゲストログイン
  devise_scope :user do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    get "/" => "homes#top"
    resources :tags, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      # ユーザーの投稿一覧
      member do
        get :posts
      end
    end

    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end


  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"

    resources :users, only: [:show, :edit, :update, :destroy] do
      get "/unsubscribe" => "users#unsubscribe"
      # ブックマークした投稿一覧表示
      member do
        get :bookmarks
      end
    end

    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      # 下書き一覧
      collection do
        get "draft_index"
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true

  # ゲストログイン
  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # プロフィール画像
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/javascript/images/no_image.png")
      profile_image.attach(io: File.open(file_path), filename: "no_image.png", content_type: "image/png")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!


  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def posts
    @user = User.find(params[:id])
    @user_posts = @user.posts.where(is_draft: false).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to admin_user_path(@user), notice: "ゲストユーザーは編集できません"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to admin_user_path(@user), notice: "ゲストユーザーは削除できません"
    else
      @user.destroy
      redirect_to admin_users_path
    end
  end

  def unsubscribe
    @user = User.find(params: id)
  end


  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image, :email, :is_deleted)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto py-5">
      <h3><span class="public-title"><i class="fas fa-user-edit"></i><%= @user.name %>さんの情報編集</span></h3>
    </div>
  </div>

  <div class="form-group d-flex justify-content-center">
    <%= render "public/posts/error", obj: @user %>
    <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
      <%= render "public/users/form", f: f %>
      <div class="form-group row">
        <div class="col-md-6"></div>
        <label class="col-md-6 col-form-label">
          <%= f.radio_button :is_deleted, false, checked: true %>
          有効
          <%= f.radio_button :is_deleted, true%>
          利用停止
        </label>
      </div>
      <div class="actions d-flex justify-content-center pb-5">
        <%= link_to "戻る", admin_user_path(@user), class: 'btn btn-outline-success btn-sm mr-3' %>
        <%= f.submit "更新する", class: 'btn btn-outline-info btn-sm ml-3' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-3 offset-2 pt-5">
      <h3><span class="admin-title">会員一覧</span></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mx-auto pt-5">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(50,50) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "詳細へ" ,admin_user_path(user), class: 'btn btn-sm btn-outline-info' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mx-auto pt-5 d-flex justify-content-center">
      <p><%= paginate @users %></p>
    </div>
  </div>
</div>

app/views/admin/users/posts.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto pt-5">
      <h3><span class="admin-title"><%= "#{@user.name}さんの投稿一覧" %></span></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mx-auto pt-5">
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>投稿日時</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @user_posts.each do |user_post| %>
          <tr>
            <td><%= user_post.title %></td>
            <td><%= user_post.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to '詳細へ', admin_post_path(user_post), class: 'btn btn-outline-info' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= link_to admin_user_path(@user), class: 'btn btn-sm mb-5' do %>
        <i class="fas fa-angle-double-left"></i> Back
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto pt-5">
      <h3><span class="admin-title"><%= @user.name %>さんの詳細ページ</span></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mx-auto my-5">
      <table class="table table-borderless">
        <tr>
          <td><%= image_tag @user.get_profile_image(100,100), class: 'border'%></td>
          <td></td>
        </tr>
        <tr>
          <th>ユーザーネーム</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td><i class="far fa-sticky-note"></i><%= link_to "#{@user.name}さんの投稿一覧", posts_admin_user_path(@user), class: 'text-dark border-bottom ml-1' %></td>
        </tr>
        <tr>
          <% unless @user.name == 'guestuser' %>
            <td><i class="fas fa-user-edit"></i><%= link_to "編集する", edit_admin_user_path(@user), class: 'text-dark border-bottom ml-1' %></td>
          <% end %>
        </tr>
        <tr>
          <% if @user.is_deleted? %>
            <td style="font-weight: bold; color: red;">利用停止中です</td>
          <% else %>
            <td style="font-weight: bold; color: green;">有効な会員です</td>
          <% end %>
        </tr>
        <tr>
          <td></td>
          <td>
            <% unless @user.name == 'guestuser' %>
              <%= link_to "このユーザーを完全に削除する", admin_user_path(@user), method: :delete, class: 'btn btn-outline-danger btn-sm ml-2', data: {confirm: "本当に削除しますか？"} %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>