config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  # ゲストログイン
  devise_scope :user do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    get "/" => "homes#top"
    resources :tags, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      # ユーザーの投稿一覧
      member do
        get :posts
      end
    end

    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end


  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"

    resources :users, only: [:show, :edit, :update, :destroy] do
      get "/unsubscribe" => "users#unsubscribe"
      # ブックマークした投稿一覧表示
      member do
        get :bookmarks
      end
    end

    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      # 下書き一覧
      collection do
        get "draft_index"
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_one_attached :post_image

  geocoded_by :address
  after_validation :geocode

  scope :latest, -> { order(created_at: :desc) }
  scope :draft, -> { where(is_draft: true) }
  scope :release, -> { where(is_draft: false) }


  with_options presence: true, on: :publicize do
    validates :title
    validates :body
    validates :airport
  end

  validates :title, length: { maximum: 20 }, on: :publicize
  validates :body, length: { maximum: 80 }, on: :publicize


  def get_post_image
    unless post_image.attached?
      file_path = Rails.root.join("app/javascript/images/no_post_image.png")
      post_image.attach(io: File.open(file_path), filename: "no_post_image.png", content_type: "image/png")
    end
    post_image
  end

  # ブックマークがあるか
  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, length: { maximum: 30 }, presence: true
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :name, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true

  # ゲストログイン
  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # プロフィール画像
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/javascript/images/no_image.png")
      profile_image.attach(io: File.open(file_path), filename: "no_image.png", content_type: "image/png")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.where(is_draft: false).order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @comments = @post.post_comments.order(created_at: :desc).page(params[:page]).per(5)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!


  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      @tags = Tag.all
      render "index"
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
    else
      render "edit"
    end
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!


  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def posts
    @user = User.find(params[:id])
    @user_posts = @user.posts.where(is_draft: false).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to admin_user_path(@user), notice: "ゲストユーザーは編集できません"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to admin_user_path(@user), notice: "ゲストユーザーは削除できません"
    else
      @user.destroy
      redirect_to admin_users_path
    end
  end

  def unsubscribe
    @user = User.find(params: id)
  end


  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image, :email, :is_deleted)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search

  def set_search
    @search = Post.left_joins(:tags).release.ransack(params[:q])
    posts = @search.result(distinct: true)
    @posts = posts.latest.page(params[:page])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-4">
      <p>空港周辺の情報を集めたコミュニティサイト</p>
      <a class="navbar-brand p-3 text-dark" href="/">
        <h4 class="logo">
          <span class="logo__maintitle">AIRSUPPORT</span>
          <span class="logo__description">Enjoy Trip More!!!
            <i class="fas fa-plane-departure" style="color: #ff7f50;"></i>
          </span>
        </h4>
      </a>
    </div>
    <div class="col-md-8">
      <h6 class="text-dark mt-5 mb-3">Link</h6>
      <ul class="p-0 list-unstyled">
        <li>
          <%= link_to 'AIRSUPPORTについて', about_path, class: 'text-black-50' %>
        </li>
        <li>
          <%= link_to '管理者ページ', new_admin_session_path, class: 'text-black-50' %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <div class="logo mr-5">
        <span class="logo__maintitle">AIRSUPPORT</span>
        <span class="logo__description">Enjoy Trip More!
          <i class="fas fa-plane-departure" style="color: #ff7f50;"></i>
        </span>
      </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-column align-items-end" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to posts_path, class: 'nav-link link-border' do %>
              <i class="far fa-copy"></i>
              投稿一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: 'nav-link link-border' do %>
              <i class="fas fa-plus"></i>
              新規投稿
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user.id), class: 'nav-link link-border' do %>
              <i class="far fa-user"></i>
              マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link link-border' do %>
              <i class="fas fa-sign-out-alt"></i>
              ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_users_path, class: 'nav-link link-border' do %>
              <i class="fas fa-users"></i>
              会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_posts_path, class: 'nav-link link-border' do %>
              <i class="far fa-copy"></i>
              投稿一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_tags_path, class: 'nav-link link-border' do %>
              <i class="fas fa-tags"></i>
              タグ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link link-border' do %>
              <i class="fas fa-sign-out-alt"></i>
              ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link link-border' do %>
              <i class="fas fa-user-plus"></i>
              会員登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link link-border' do %>
              <i class="fas fa-sign-in-alt"></i>
              ログイン
          <% end %>
          </li>
          <li class="nav-item">
            <%= link_to public_guest_sign_in_path, class: 'nav-link link-border', method: :post do %>
              <i class="fas fa-users"></i>
              ゲストログイン
            <% end %>
          </li>
        <% end %>
      </ul>
      <% if admin_signed_in? %>
        <div class='d-flex justify-content-end'>*管理者でログインしています</div>
      <% else %>
        <div class="nav-item mt-3">
          <%= search_form_for @search, url: posts_path, class: ' d-flex align-items-center' do |f| %>
            <i class="fas fa-search fa-lg mr-3" style="color: #52616b;"></i>
            <%= f.search_field :title_cont, placeholder: 'キーワードで検索...', value: "", class: 'form-control' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>airsupport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm sticky-top">
      <%= render "layouts/header" %>
    </header>

    <main>
      <%= flash[:notice] %>
      <%= flash[:alert] %>
    <%= yield %>
    </main>

    <footer class="bg-light text-black footer mt-auto py-3">
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>